# Swagger file modified to run swagger2api tool from Apigee
swagger: '2.0'
info:
  version: v1
  title: GMF MyAccount PoC APIs
host: amer-partner9-test.apigee.net
basePath: /poc-gmf-ma/v1
schemes:
  - http
  - https
consumes:
  - application/json
produces:
  - application/json
paths:
  /customers/{customerId}:
    x-swagger-router-controller: customers #Apigee Tag
    parameters:
      - name: apikey
        in: header
        description: API Key to call the API
        required: true
        type: string
    get:
      tags:
        - customers
      summary: Get a specific customer by Id
      description: Get a specific customer by Id
      operationId: customers #Apigee Tag
      parameters:
        - name: customerId
          in: path
          description: Unique Id of the customer to fetch
          required: true
          type: string
      responses:
        '200':
          description: Response for resource retrieved
          schema:
            $ref: '#/definitions/customer-response'
        default:
          description: Error
          schema:
            $ref: '#/definitions/ErrorResponse'
definitions:
  ErrorResponse:
    required:
      - message
    properties:
      message:
        type: string
  customer-response:
    type: object
    properties:
      data:
        type: array
        items:
          $ref: './definitions/gmf-customer.schema'
